name: Build

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      # - name: Install golang deps
      #   run: ./install-go-dependencies.sh
      - name: Install system python deps
        run: sudo apt update && sudo apt install python3-ply python3-pil libjpeg-dev zlib1g-dev
      - name: Get setuptools
        run: pip install --upgrade setuptools
      - name: Install pytest
        run: pip install pytest coverage
      - name: Install dependencies
        run: pip install .
      - name: Build
        run: poetry build
